### ISSUE TITLE
Import error for trilinear package

### ISSUE THREAD

**Issue by johnoh0966** [bcmi/libcom#36]
```
Traceback (most recent call last):
  File "C:\Users\userAdmin\Documents\TechDev\cdf_demo\LipSick\inference.py", line 1, in <module>
    from libcom import ImageHarmonizationModel
  File "C:\Users\userAdmin\miniconda3\envs\lipsick\lib\site-packages\libcom-0.0.2.post1-py3.10-win-amd64.egg\libcom\__init__.py", line 6, in <module>
    from .image_harmonization import *
  File "C:\Users\userAdmin\miniconda3\envs\lipsick\lib\site-packages\libcom-0.0.2.post1-py3.10-win-amd64.egg\libcom\image_harmonization\__init__.py", line 2, in <module>    from .image_harmonization import ImageHarmonizationModel
  File "C:\Users\userAdmin\miniconda3\envs\lipsick\lib\site-packages\libcom-0.0.2.post1-py3.10-win-amd64.egg\libcom\image_harmonization\image_harmonization.py", line 8, 
in <module>
    from .source.pct_net import *
  File "C:\Users\userAdmin\miniconda3\envs\lipsick\lib\site-packages\libcom-0.0.2.post1-py3.10-win-amd64.egg\libcom\image_harmonization\source\pct_net.py", line 6, in <module>
    from .functions import PCT, ViT_Harmonizer
  File "C:\Users\userAdmin\miniconda3\envs\lipsick\lib\site-packages\libcom-0.0.2.post1-py3.10-win-amd64.egg\libcom\image_harmonization\source\functions.py", line 11, in <module>
    import trilinear
ImportError: DLL load failed while importing trilinear: The specified module could not be found.
```

Hi, I created a new environment and have ran the setup.sh scripts for both libcom and trilinear which can be seen in my environment libraries and also when calling pip list but keep encountering this error. Is there a way to resolve this?

**Comment by ustcnewly** [comment]
You can refer to “Tips: If you encounter any issues during installation related to the trilinear library“ in https://github.com/bcmi/libcom/blob/main/docs/get_started.md
