### ISSUE TITLE
modelscope.hub.errors.NotExistError

### ISSUE THREAD

**Issue by rimu123** [bcmi/libcom#6]
Traceback (most recent call last):
  File "tests/test_fopa_heat_map.py", line 19, in <module>
    net = FOPAHeatMapModel(device=0)
  File "/home/largedata/qianlei/parking_slot_detection/libcom/libcom/fopa_heat_map/fopa_heat_map.py", line 68, in __init__
    download_pretrained_model(sopa_weight)
  File "/home/largedata/qianlei/parking_slot_detection/libcom/libcom/utils/model_download.py", line 18, in download_pretrained_model
    download_file_from_network(model_name, save_dir)
  File "/home/largedata/qianlei/parking_slot_detection/libcom/libcom/utils/model_download.py", line 50, in download_file_from_network
    file_path = model_file_download(model_id=ms_repo, 
  File "/home/qianlei/miniconda3/envs/Libcom/lib/python3.8/site-packages/modelscope/hub/file_download.py", line 136, in model_file_download
    raise NotExistError('The file path: %s not exist in: %s' %
modelscope.hub.errors.NotExistError: The file path: SOPA.pth.tar not exist in: bcmizb/Libcom_pretrained_models

Hello, failed to download the model. I tried to open the download link, but it couldn't be opened.

**Comment by bo-zhang-cs** [comment]
Thanks for your report! We have fixed this bug. You can try the latest version by running ``pip install --upgrade libcom`` and downloading the source code, then try again.
